name: Action

on: 
  push:

jobs:

  run_c_programs:
    name: Run C Programs
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: C Compiler Check
        run: cc --version

      - name: Compile and Run C Code
        working-directory: ./src
        run: |
          bash ../scripts/automate
