name: Action
on: 
  push:

jobs:

  run_c_programs:
    name: run c programs
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: C Compiler Check
        run: cc --version

      # I'll modify this later
      - name: Compile and Run C Code
        working-directory: ./source
        run: |
          for dir in *;
          do
           
            [[ -z "$(ls $dir)" ]] && continue || echo -e "\e[4;32m$dir\e[0m\n" && cd $dir;

            for file in *;
            do
              echo -e "\e[1;32m${file}\e[0m:";
              cc $file && ./a.out && rm $_ && sleep 0.25 && echo -e "\n"
            done
            
            cd ..;
          done
          exit
